export const authConstants = {
    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
    VIEWS_REQUEST: "USERS_VIEWS_REQUEST",
    VIEWS_SUCCESS: "USERS_VIEWS_SUCCESS",
    VIEWS_FAILURE: "USERS_VIEWS_FAILURE",

    LOGOUT: "USERS_LOGOUT",
}